[project]
authors = ["Silvio Traversaro <silvio@traversaro.it>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "reproduce-rattler"
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
reproduce = "rattler-build build -m ./conda_build_config.yaml"

[dependencies]
rattler-build = "*"
