package:
  name: nonrelocatable-split
  version: 0.0.1

# dummy source, otherwise conda-build does not work properly
source:
  url: https://github.com/robotology/ycm/archive/refs/tags/v0.18.1.tar.gz
  sha256: 1e621f3af47ed1c3d1cce68e4caeae406785c1ae703a30cb146c27a946d175e8


build:
  number: 0

outputs:
  - name: nonrelocatable
    script: build_cmake.sh  # [unix]
    script: bld_cmake.bat  # [win]
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

    test:
      commands:
        - cmake-package-check --disable-double-find nonrelocatable
      requires:
        - cmake-package-check
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

about:
  home: https://github.com/robotology/ycm
  license: BSD-3-Clause
  license_file: ../src/LICENSE
  summary: Extra CMake Modules for YARP and friends.

